llm:
  mode: local
  max_new_tokens: 512
  context_window: 2048
  tokenizer: microsoft/phi-2

local:
  prompt_style: "chatml"
  llm_hf_repo_id: TheBloke/dolphin-2_6-phi-2-GGUF
  llm_hf_model_file: dolphin-2_6-phi-2.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5